//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExampleText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExampleText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceDemo.Resources.ExampleText", typeof(ExampleText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The demo is a example project about how to use resource file(.resx)..
        /// </summary>
        public static string Message_About_Demo {
            get {
                return ResourceManager.GetString("Message_About_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string Message_Hello {
            get {
                return ResourceManager.GetString("Message_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morafterevening！{0}！.
        /// </summary>
        public static string Message_HelloWithName {
            get {
                return ResourceManager.GetString("Message_HelloWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue....
        /// </summary>
        public static string Mutual_IntoNextMessage {
            get {
                return ResourceManager.GetString("Mutual_IntoNextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after into next, plz tell me u name.
        /// </summary>
        public static string Mutual_TellMeYourName {
            get {
                return ResourceManager.GetString("Mutual_TellMeYourName", resourceCulture);
            }
        }
    }
}
